name: nbscribe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - jupyterlab
  - nbformat
  - jinja2
  - pip:
    - fastapi
    - uvicorn[standard]
    - python-multipart
    - httpx
    - openai
    - python-dotenv
    - langchain
    - langchain-openai
    - beautifulsoup4
    - websockets 
    - nbformat>=5.9,<6
    - jupyter_client>=8.6,<9
    - ipykernel>=6.29,<7
    - bleach>=6.1,<7