name: nbscribe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - jupyterlab
  - nbformat
  - jinja2
  - pip:
    - fastapi
    - uvicorn[standard]
    - python-multipart
    - httpx
    - openai
    - python-dotenv
    - langchain
    - langchain-openai
    - beautifulsoup4
    - websockets 